### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by kirb** [TapSharp/UnicodeFaces#1]
You are using the settings icon from Cobalia. Please change or remove it. I think it's fair to assume an icon shouldn't be used by multiple tweaks, it creates confusion and makes the tweak seem like it might have been ripped off from other people's work.

**Comment by neoighodaro** [comment]
Yes, sorry. Was an oversight, was always meaning to do this. I actually had it on multiple tweaks. I'll be removing them on the next release. Thanks.
